

services:
  governance-backend-server:
    image: governance-backend
    container_name: governance-backend-server
    command: ["governance-server"]
    environment:
      NODE_ENV: production
      WEB_SERVER_PORT: 9500
      DB_TYPE: mysql
      DB_HOST: governance-backend-db
      DB_PORT: 3306
      DB_DATABASE: governancedb
      DB_USERNAME: governanceuser
      DB_PASSWORD: governancepass
      CONNECTED_CONFIGS: "configs/networks/coston2.json"
      CONFIG_FILE: "configs/networks/coston2.json"
      RPC: "https://api.flare.network/coston2/bc/C/rpc?x-apikey=apikey"
      MAX_BLOCKS_FOR_EVENT_READS: 30
      INDEXING_START_BLOCK: 2000000
    restart: unless-stopped
    ports:
      - 9500:9500

  governance-backend-event-collector:
    image: governance-backend
    container_name: governance-backend-event-collector
    command: ["governance-event-collector"]
    environment:
      NODE_ENV: production
      WEB_SERVER_PORT: 9500
      DB_TYPE: mysql
      DB_HOST: governance-backend-db
      DB_PORT: 3306
      DB_DATABASE: governancedb
      DB_USERNAME: governanceuser
      DB_PASSWORD: governancepass
      CONNECTED_CONFIGS: "configs/networks/coston2.json"
      CONFIG_FILE: "configs/networks/coston2.json"
      RPC: "https://api.flare.network/coston2/bc/C/rpc?x-apikey=apikey"
      MAX_BLOCKS_FOR_EVENT_READS: 30
      INDEXING_START_BLOCK: 2000000
    restart: unless-stopped

  governance-backend-db:
    image: mysql:8-debian
    container_name: governance-backend-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: governanceuser
      MYSQL_DATABASE: governancedb
      MYSQL_PASSWORD: governancepass
    restart: unless-stopped
    ports:
      - 3369:3306



